<?php
/**
 * Created by PhpStorm.
 * User: intern
 * Date: 2017/11/25
 * Time: 下午3:25
 */
class shape {
    public function draw(){

    }
}

class circle extends shape {
    public function draw($origin,$radius)
    {
        if ($radius > 0) {
            parent::draw(); // TODO: Change the autogenerated stub
            return true;
        }
        return false;

    }
}

//combine() 可以完成数字相加,连接字符串,合并数组
function combine($a,$b) {
    if (is_int($a) && is_int($b)) {
        return $a + $b;
    }
    if (is_float($a) && is_float($b)) {
        return $a + $b;
    }

}